using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using SheepGate.Core;
using UnityEngine;

namespace SheepGate.Scripture
{
    /// <summary>Single verse as stored in the generated verses.json.</summary>
    public class VerseEntry
    {
        public string ref_display;
        public string text;
    }

    /// <summary>One numbered verse inside a chapter entry.</summary>
    public class ChapterVerse
    {
        public int n;
        public string text;
    }

    /// <summary>A whole chapter, used by the in-app reader.</summary>
    public class ChapterEntry
    {
        public string ref_display;
        public ChapterVerse[] verses;
    }

    /// <summary>Translation metadata carried by the generated file.</summary>
    public class VersionInfo
    {
        public string id;
        public string abbrev;
        public string copyright;
    }

    /// <summary>
    /// In-memory index over Resources/Data/locales/&lt;locale&gt;/verses.json.
    /// Loaded once per locale, never touches the network, never invents text: a lookup miss
    /// returns a visible marker so the gap is obvious on screen instead of silent.
    /// The file itself is generated by tools/fetch-verses.mjs and is never hand edited.
    ///
    /// The index is per locale because a translation is a different set of words for the same
    /// references. The references themselves never move, which is why nothing outside this file
    /// has to know a locale is involved at all.
    /// </summary>
    public static class ScriptureService
    {
        private const string VersesFileName = "/verses";
        private const string UnknownReference = "?";

        /// <summary>Resources path of the generated file for a locale, without extension.</summary>
        public static string ResourcePathFor(string locale)
        {
            return Locales.ResourceFolder(locale) + VersesFileName;
        }

        /// <summary>Resources path of the file backing the index in memory.</summary>
        public static string ResourcePath
        {
            get { return ResourcePathFor(LoadedLocale); }
        }

        /// <summary>The locale whose scripture is in memory. Empty before the first load.</summary>
        public static string LoadedLocale
        {
            get { return _loadedLocale ?? string.Empty; }
        }

        private static string _loadedLocale;

        private static readonly Dictionary<string, VerseEntry> VerseIndex =
            new Dictionary<string, VerseEntry>(StringComparer.OrdinalIgnoreCase);

        private static readonly Dictionary<string, ChapterEntry> ChapterIndex =
            new Dictionary<string, ChapterEntry>(StringComparer.OrdinalIgnoreCase);


        // Defaults are the pessimistic ones: until a real file proves otherwise the
        // build is treated as a placeholder and the version block is empty but non-null.
        private static bool _isPlaceholderBuild = true;
        private static VersionInfo _version = new VersionInfo();

        /// <summary>True when verses.json was generated without a real fetch.</summary>
        public static bool IsPlaceholderBuild
        {
            get
            {
                EnsureLoaded();
                return _isPlaceholderBuild;
            }
        }

        /// <summary>Translation metadata. Never null; fields may be null when unknown.</summary>
        public static VersionInfo Version
        {
            get
            {
                EnsureLoaded();
                return _version;
            }
        }

        /// <summary>Reads the active locale's verses.json into memory. Safe to call more than once.</summary>
        public static void Load()
        {
            Load(Locales.Active);
        }

        /// <summary>Rereads for whichever locale is active. Used when the language changes.</summary>
        public static void Reload()
        {
            Load(Locales.Active, true);
        }

        /// <summary>
        /// Reads one locale's verses.json into memory. A second call for the same locale is a no-op
        /// unless <paramref name="force"/> is set.
        /// </summary>
        public static void Load(string locale, bool force = false)
        {
            string canonical = Locales.Canonical(locale) ?? Locales.Source;
            if (!force && _loadedLocale == canonical)
            {
                return;
            }

            _loadedLocale = canonical;
            VerseIndex.Clear();
            ChapterIndex.Clear();
            _isPlaceholderBuild = true;
            _version = new VersionInfo();

            string path = ResourcePathFor(canonical);
            TextAsset asset = Resources.Load<TextAsset>(path);
            if (asset == null)
            {
                Debug.LogError(
                    "ScriptureService: Resources/" + path +
                    ".json not found. Run: node tools/fetch-verses.mjs --locale " + canonical);
                return;
            }

            ScriptureDocument document = null;
            try
            {
                document = JsonConvert.DeserializeObject<ScriptureDocument>(asset.text);
            }
            catch (Exception exception)
            {
                Debug.LogError("ScriptureService: failed to parse verses.json - " + exception.Message);
                return;
            }

            if (document == null)
            {
                Debug.LogError("ScriptureService: verses.json parsed to nothing.");
                return;
            }

            _isPlaceholderBuild = document.is_placeholder;

            if (document.version != null)
            {
                _version = document.version;
            }

            if (document.verses != null)
            {
                foreach (KeyValuePair<string, VerseEntry> pair in document.verses)
                {
                    string key = Normalize(pair.Key);
                    VerseEntry entry = pair.Value;
                    if (key.Length == 0 || entry == null)
                    {
                        continue;
                    }

                    if (string.IsNullOrEmpty(entry.ref_display))
                    {
                        entry.ref_display = key;
                    }

                    VerseIndex[key] = entry;
                }
            }

            if (document.chapters != null)
            {
                foreach (KeyValuePair<string, ChapterEntry> pair in document.chapters)
                {
                    string key = Normalize(pair.Key);
                    ChapterEntry entry = pair.Value;
                    if (key.Length == 0 || entry == null)
                    {
                        continue;
                    }

                    if (string.IsNullOrEmpty(entry.ref_display))
                    {
                        entry.ref_display = key;
                    }

                    if (entry.verses == null)
                    {
                        entry.verses = new ChapterVerse[0];
                    }

                    ChapterIndex[key] = entry;
                }
            }

            if (_isPlaceholderBuild)
            {
                Debug.LogWarning(
                    "ScriptureService: placeholder scripture for locale " + canonical +
                    " - every verse renders the unavailable-text marker. " +
                    "Run: node tools/fetch-verses.mjs --provider youversion --locale " + canonical);
            }
        }

        /// <summary>Looks up a verse by reference, for example NEH.4.6.</summary>
        public static bool TryGetVerse(string reference, out VerseEntry verse)
        {
            EnsureLoaded();
            verse = null;

            string key = Normalize(reference);
            if (key.Length == 0)
            {
                return false;
            }

            VerseEntry found;
            if (!VerseIndex.TryGetValue(key, out found) || found == null)
            {
                return false;
            }

            // An empty text is a miss: better a visible marker than a blank bubble.
            if (string.IsNullOrEmpty(found.text))
            {
                return false;
            }

            verse = found;
            return true;
        }

        /// <summary>Never null. On a miss the text is the visible unavailable marker.</summary>
        public static VerseEntry GetVerse(string reference)
        {
            VerseEntry verse;
            if (TryGetVerse(reference, out verse))
            {
                return verse;
            }

            string display = Normalize(reference);
            if (display.Length == 0)
            {
                display = UnknownReference;
            }

            return new VerseEntry
            {
                ref_display = display,
                text = MissingMarker(display)
            };
        }

        /// <summary>Looks up a whole chapter by chapter reference, for example NEH.4.</summary>
        public static bool TryGetChapter(string chapterRef, out ChapterEntry chapter)
        {
            EnsureLoaded();
            chapter = null;

            string key = Normalize(chapterRef);
            if (key.Length == 0)
            {
                return false;
            }

            ChapterEntry found;
            if (!ChapterIndex.TryGetValue(key, out found) || found == null)
            {
                return false;
            }

            if (found.verses == null || found.verses.Length == 0)
            {
                return false;
            }

            chapter = found;
            return true;
        }

        /// <summary>Never null. On a miss returns a single verse holding the unavailable marker.</summary>
        public static ChapterEntry GetChapter(string chapterRef)
        {
            ChapterEntry chapter;
            if (TryGetChapter(chapterRef, out chapter))
            {
                return chapter;
            }

            string display = Normalize(chapterRef);
            if (display.Length == 0)
            {
                display = UnknownReference;
            }

            return new ChapterEntry
            {
                ref_display = display,
                verses = new[]
                {
                    new ChapterVerse { n = 1, text = MissingMarker(display) }
                }
            };
        }

        /// <summary>
        /// A chapter reference in the words a player reads — "Neemias 3", never the id "NEH.3".
        ///
        /// Ids are ours, not theirs: a screen that prints NEH.3 is showing the player a database
        /// key. Three fallbacks, in order of how much they can be trusted: the chapter's own
        /// ref_display when the chapter is packaged; otherwise any packaged verse of that chapter
        /// with its verse number trimmed off; otherwise the id, because a visible id is at least
        /// something somebody will notice and fix.
        ///
        /// The trim is by the last ':' in the display, which holds for both languages this ships
        /// in. A translation that separates chapter and verse some other way needs its own case
        /// here rather than a silently wrong answer.
        /// </summary>
        public static string ChapterDisplay(string chapterRef)
        {
            string key = Normalize(chapterRef);
            if (key.Length == 0)
            {
                return UnknownReference;
            }

            ChapterEntry chapter;
            if (TryGetChapter(key, out chapter) && chapter != null && !string.IsNullOrEmpty(chapter.ref_display))
            {
                return chapter.ref_display;
            }

            string prefix = key + ".";
            foreach (KeyValuePair<string, VerseEntry> pair in VerseIndex)
            {
                if (pair.Key == null || !pair.Key.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                string display = pair.Value != null ? pair.Value.ref_display : null;
                if (string.IsNullOrEmpty(display))
                {
                    continue;
                }

                int separator = display.LastIndexOf(':');
                return separator > 0 ? display.Substring(0, separator) : display;
            }

            return key;
        }

        /// <summary>NEH.4.6 becomes NEH.4. A reference that is already a chapter is returned as is.</summary>
        public static string ChapterRefOf(string verseRef)
        {
            string key = Normalize(verseRef);
            if (key.Length == 0)
            {
                return string.Empty;
            }

            string[] parts = key.Split('.');
            if (parts.Length < 3)
            {
                return key;
            }

            return parts[0] + "." + parts[1];
        }

        private static void EnsureLoaded()
        {
            if (string.IsNullOrEmpty(_loadedLocale))
            {
                Load();
            }
        }

        /// <summary>
        /// The visible stand-in for text that could not be resolved. Player facing, so it is a
        /// localised string like every other: no sentence a player can read is written in C#.
        /// </summary>
        private static string MissingMarker(string display)
        {
            return Loc.T("scripture.unavailable", display);
        }

        private static string Normalize(string reference)
        {
            return reference == null ? string.Empty : reference.Trim();
        }

        /// <summary>Shape of the generated verses.json. Mirrors tools/fetch-verses.mjs output.</summary>
        private class ScriptureDocument
        {
            [JsonProperty("version")]
            public VersionInfo version;

            [JsonProperty("is_placeholder")]
            public bool is_placeholder;

            [JsonProperty("verses")]
            public Dictionary<string, VerseEntry> verses;

            [JsonProperty("chapters")]
            public Dictionary<string, ChapterEntry> chapters;
        }
    }
}
