using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;

namespace SheepGate.Scripture
{
    /// <summary>Single verse as stored in the generated verses.json.</summary>
    public class VerseEntry
    {
        public string ref_display;
        public string text;
    }

    /// <summary>One numbered verse inside a chapter entry.</summary>
    public class ChapterVerse
    {
        public int n;
        public string text;
    }

    /// <summary>A whole chapter, used by the in-app reader.</summary>
    public class ChapterEntry
    {
        public string ref_display;
        public ChapterVerse[] verses;
    }

    /// <summary>Translation metadata carried by the generated file.</summary>
    public class VersionInfo
    {
        public string id;
        public string abbrev;
        public string copyright;
    }

    /// <summary>
    /// In-memory index over Resources/Data/verses.json.
    /// Loaded once, never touches the network, never invents text: a lookup miss
    /// returns a visible marker so the gap is obvious on screen instead of silent.
    /// The file itself is generated by tools/fetch-verses.mjs and is never hand edited.
    /// </summary>
    public static class ScriptureService
    {
        /// <summary>Resources path of the generated data file, without extension.</summary>
        public const string ResourcePath = "Data/verses";

        // Player-facing marker, pt-BR. Written with escapes so the source file stays
        // pure ASCII and cannot be mangled by a compiler running under a non-UTF-8 codepage.
        // Renders as: <angle>texto indisponivel - NEH.4.6<angle> with the proper accents.
        private const string MissingTextPrefix = "\u27E8texto indispon\u00EDvel \u2014 ";
        private const string MissingTextSuffix = "\u27E9";
        private const string UnknownReference = "?";

        private static readonly Dictionary<string, VerseEntry> VerseIndex =
            new Dictionary<string, VerseEntry>(StringComparer.OrdinalIgnoreCase);

        private static readonly Dictionary<string, ChapterEntry> ChapterIndex =
            new Dictionary<string, ChapterEntry>(StringComparer.OrdinalIgnoreCase);

        private static bool _loaded;

        // Defaults are the pessimistic ones: until a real file proves otherwise the
        // build is treated as a placeholder and the version block is empty but non-null.
        private static bool _isPlaceholderBuild = true;
        private static VersionInfo _version = new VersionInfo();

        /// <summary>True when verses.json was generated without a real fetch.</summary>
        public static bool IsPlaceholderBuild
        {
            get
            {
                EnsureLoaded();
                return _isPlaceholderBuild;
            }
        }

        /// <summary>Translation metadata. Never null; fields may be null when unknown.</summary>
        public static VersionInfo Version
        {
            get
            {
                EnsureLoaded();
                return _version;
            }
        }

        /// <summary>Reads Resources/Data/verses.json into memory. Safe to call more than once.</summary>
        public static void Load()
        {
            if (_loaded)
            {
                return;
            }

            _loaded = true;

            TextAsset asset = Resources.Load<TextAsset>(ResourcePath);
            if (asset == null)
            {
                Debug.LogError(
                    "ScriptureService: Resources/" + ResourcePath +
                    ".json not found. Run: node tools/fetch-verses.mjs --placeholder");
                return;
            }

            ScriptureDocument document = null;
            try
            {
                document = JsonConvert.DeserializeObject<ScriptureDocument>(asset.text);
            }
            catch (Exception exception)
            {
                Debug.LogError("ScriptureService: failed to parse verses.json - " + exception.Message);
                return;
            }

            if (document == null)
            {
                Debug.LogError("ScriptureService: verses.json parsed to nothing.");
                return;
            }

            _isPlaceholderBuild = document.is_placeholder;

            if (document.version != null)
            {
                _version = document.version;
            }

            if (document.verses != null)
            {
                foreach (KeyValuePair<string, VerseEntry> pair in document.verses)
                {
                    string key = Normalize(pair.Key);
                    VerseEntry entry = pair.Value;
                    if (key.Length == 0 || entry == null)
                    {
                        continue;
                    }

                    if (string.IsNullOrEmpty(entry.ref_display))
                    {
                        entry.ref_display = key;
                    }

                    VerseIndex[key] = entry;
                }
            }

            if (document.chapters != null)
            {
                foreach (KeyValuePair<string, ChapterEntry> pair in document.chapters)
                {
                    string key = Normalize(pair.Key);
                    ChapterEntry entry = pair.Value;
                    if (key.Length == 0 || entry == null)
                    {
                        continue;
                    }

                    if (string.IsNullOrEmpty(entry.ref_display))
                    {
                        entry.ref_display = key;
                    }

                    if (entry.verses == null)
                    {
                        entry.verses = new ChapterVerse[0];
                    }

                    ChapterIndex[key] = entry;
                }
            }

            if (_isPlaceholderBuild)
            {
                Debug.LogWarning(
                    "ScriptureService: placeholder build - every verse renders the unavailable-text marker. " +
                    "Run: node tools/fetch-verses.mjs --provider youversion");
            }
        }

        /// <summary>Looks up a verse by reference, for example NEH.4.6.</summary>
        public static bool TryGetVerse(string reference, out VerseEntry verse)
        {
            EnsureLoaded();
            verse = null;

            string key = Normalize(reference);
            if (key.Length == 0)
            {
                return false;
            }

            VerseEntry found;
            if (!VerseIndex.TryGetValue(key, out found) || found == null)
            {
                return false;
            }

            // An empty text is a miss: better a visible marker than a blank bubble.
            if (string.IsNullOrEmpty(found.text))
            {
                return false;
            }

            verse = found;
            return true;
        }

        /// <summary>Never null. On a miss the text is the visible pt-BR unavailable marker.</summary>
        public static VerseEntry GetVerse(string reference)
        {
            VerseEntry verse;
            if (TryGetVerse(reference, out verse))
            {
                return verse;
            }

            string display = Normalize(reference);
            if (display.Length == 0)
            {
                display = UnknownReference;
            }

            return new VerseEntry
            {
                ref_display = display,
                text = MissingMarker(display)
            };
        }

        /// <summary>Looks up a whole chapter by chapter reference, for example NEH.4.</summary>
        public static bool TryGetChapter(string chapterRef, out ChapterEntry chapter)
        {
            EnsureLoaded();
            chapter = null;

            string key = Normalize(chapterRef);
            if (key.Length == 0)
            {
                return false;
            }

            ChapterEntry found;
            if (!ChapterIndex.TryGetValue(key, out found) || found == null)
            {
                return false;
            }

            if (found.verses == null || found.verses.Length == 0)
            {
                return false;
            }

            chapter = found;
            return true;
        }

        /// <summary>Never null. On a miss returns a single verse holding the unavailable marker.</summary>
        public static ChapterEntry GetChapter(string chapterRef)
        {
            ChapterEntry chapter;
            if (TryGetChapter(chapterRef, out chapter))
            {
                return chapter;
            }

            string display = Normalize(chapterRef);
            if (display.Length == 0)
            {
                display = UnknownReference;
            }

            return new ChapterEntry
            {
                ref_display = display,
                verses = new[]
                {
                    new ChapterVerse { n = 1, text = MissingMarker(display) }
                }
            };
        }

        /// <summary>NEH.4.6 becomes NEH.4. A reference that is already a chapter is returned as is.</summary>
        public static string ChapterRefOf(string verseRef)
        {
            string key = Normalize(verseRef);
            if (key.Length == 0)
            {
                return string.Empty;
            }

            string[] parts = key.Split('.');
            if (parts.Length < 3)
            {
                return key;
            }

            return parts[0] + "." + parts[1];
        }

        private static void EnsureLoaded()
        {
            if (!_loaded)
            {
                Load();
            }
        }

        private static string MissingMarker(string display)
        {
            return MissingTextPrefix + display + MissingTextSuffix;
        }

        private static string Normalize(string reference)
        {
            return reference == null ? string.Empty : reference.Trim();
        }

        /// <summary>Shape of the generated verses.json. Mirrors tools/fetch-verses.mjs output.</summary>
        private class ScriptureDocument
        {
            [JsonProperty("version")]
            public VersionInfo version;

            [JsonProperty("is_placeholder")]
            public bool is_placeholder;

            [JsonProperty("verses")]
            public Dictionary<string, VerseEntry> verses;

            [JsonProperty("chapters")]
            public Dictionary<string, ChapterEntry> chapters;
        }
    }
}
